# Generated by Django 5.2.4 on 2025-07-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call_api', '0003_alter_calllog_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='from_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='to_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
